### ISSUE TITLE
error when mirge calls cutadapter

### ISSUE THREAD

**Issue by skaffen-amtiskaw** [BarasLab/miRge#15]
I've installed mirge with all dependencies, but I am getting an error with every test I try to run. I have installed cutadapt both via pip and installing from source. Any ideas?

 perl miRge.pl --adapter illumina --species human --SampleFiles miRge.samples/human_s1.fastq

Checking for bowtie and indices ...
Bowtie and indices present (0.00 sec).

Starting quantitation pipeline ...
Processing miRge.samples/human_s1.fastq Traceback (most recent call last):
  File "/share/apps/src/miRge/trim_file.py", line 5, in <module>
    from cutadapt.scripts.cutadapt import AdapterCutter
ImportError: No module named scripts.cutadapt
rm: cannot remove ‘miRge.1517501018/human_s1.fastq.log’: No such file or directory
cpuTime-trim:0.07, cutadapt version 1.15
Copyright (C) 2010-2017 Marcel Martin <marcel.martin@scilifelab.se>

cutadapt removes adapter sequences from high-throughput sequencing reads.

Usage:
    cutadapt -a ADAPTER [options] [-o output.fastq] input.fastq

For paired-end reads:
    cutadapt -a ADAPT1 -A ADAPT2 [options] -o out1.fastq -p out2.fastq in1.fastq in2.fastq

Replace "ADAPTER" with the actual sequence of your 3' adapter. IUPAC wildcard
characters are supported. The reverse complement is *not* automatically
searched. All reads from input.fastq will be written to output.fastq with the
adapter sequence removed. Adapter matching is error-tolerant. Multiple adapter
sequences can be given (use further -a options), but only the best-matching
adapter will be removed.

Input may also be in FASTA format. Compressed input and output is supported and
auto-detected from the file name (.gz, .xz, .bz2). Use the file name '-' for
standard input/output. Without the -o option, output is sent to standard output.

Citation:

Marcel Martin. Cutadapt removes adapter sequences from high-throughput
sequencing reads. EMBnet.Journal, 17(1):10-12, May 2011.
http://dx.doi.org/10.14806/ej.17.1.200

Use "cutadapt --help" to see all command-line options.
See http://cutadapt.readthedocs.io/ for full documentation.

cutadapt: error: [Errno 2] No such file or directory: 'miRge.1517501018/human_s1.2.trim.fastq'
Error: Couldn't trim first 0 and last 0 bases!

**Comment by Chris7** [comment]
Hi @skaffen-amtiskaw 

It looks like cutadapt broke compatibility. We implemented a threaed solution here as at the time, cutadapt did not support threading. You can try installing a supported version with:
`pip install cutadapt==1.8.1`

**Comment by skaffen-amtiskaw** [comment]
You know what - I didnt see that you specified 1.8.1 - 1.10 in your docs and I just installed the latest cutadapt, 1.15. Totally my fault, it is working with 1.9.1 

Thanks for the quick response!

**Comment by Chris7** [comment]
:+1: Thanks for the report!

**Comment by alexbaras** [comment]
Thanks Chris

-Alex
